'# $(appName)/deployment.yaml
apiVersion: apps/v1beta1
kind: Deployment
metadata:
    name: $(appName)
    labels:
        app: $(appName)
spec:
    replicas: 1
    selector:
        matchLabels:
            app: $(appName)
    template:
        metadata:
            labels:
                app: $(appName)
        spec:
            containers:
                - name: $(appName)
                  image: mydockertestcontainer.azurecr.io/myakscluster2d14:$(Build.BuildId)                
                  imagePullPolicy: 
                  ports:
                    - name: http
                      containerPort: 8080
                      protocol: TCP   				  
            nodeSelector:
                  kubernetes.io/os: windows

---

# $(appName)/service.yaml
apiVersion: v1
kind: Service
metadata:
    name: $(appName)
    labels:
        app: $(appName)
spec:
    type: ClusterIP
    ports:
        - port: 8080
          targetPort: 8080
          protocol: TCP
          name: http
    selector:
        app: $(appName)

---

# $(appName)/ingress.yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
    name: $(appName)
    labels:
        app: $(appName)
    annotations:
        kubernetes.io/ingress.class: addon-http-application-routing
spec:
    rules:
        - host: $(namespace)-$(appName).12035bc0b4c64a4aa1bc.centralus.aksapp.io
          http:
            paths:
            - path: /
              backend:
                serviceName: $(appName)
                servicePort: 8080' | Set-Content $(Agent.TempDirectory)/manifest.yaml